account_id = ""
compatibility_date = "2021-11-01"
name = "cf-cloudflare-worker-s3-uploader"
main = "dist/worker.js"
workers_dev = true

[site]
bucket = "./dist"

[build]
command = "npm install && npm run build"

[vars]
S3_BUCKET = "your_bucket_name"
S3_FOLDER = "folder-name/"
S3_REGION = "s3_region_name"

[secrets]
# NAME
# PASS
# AWS_ID
# AWS_SECRET
